// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/api/mail.ts";
import * as $4 from "./routes/index.tsx";
import * as $$0 from "./islands/ContactForm.tsx";
import * as $$1 from "./islands/MouseFollower.tsx";
import * as $$2 from "./islands/Navbar.tsx";
import * as $$3 from "./islands/SimpleProject.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/api/mail.ts": $3,
    "./routes/index.tsx": $4,
  },
  islands: {
    "./islands/ContactForm.tsx": $$0,
    "./islands/MouseFollower.tsx": $$1,
    "./islands/Navbar.tsx": $$2,
    "./islands/SimpleProject.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
