// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/_layout.tsx";
import * as $4 from "./routes/contact-failed.tsx";
import * as $5 from "./routes/contact-successful.tsx";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/job.tsx";
import * as $$0 from "./islands/Navbar.tsx";
import * as $$1 from "./islands/Projects.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/_layout.tsx": $3,
    "./routes/contact-failed.tsx": $4,
    "./routes/contact-successful.tsx": $5,
    "./routes/index.tsx": $6,
    "./routes/job.tsx": $7,
  },
  islands: {
    "./islands/Navbar.tsx": $$0,
    "./islands/Projects.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
